### ISSUE TITLE
Docker Hub update

### ISSUE THREAD

**Issue by johnwc** [litespeedtech/ols-dockerfiles#2]
The last release to docker hub is 1.6.18, can we get the two updates since then published as well?

**Comment by Code-Egg** [comment]
Sure, the latest version has been committed to the repo but no auto-build due to run out of credit on Travis, let's see if it will start auto-build in March. I will manually build if it still not working.

**Comment by johnwc** [comment]
Thank you

**Comment by Code-Egg** [comment]
@johnwc  
I just set up the GitHub workflow, 1.6.20 is now on the docker hub, let me know if it works for you.
