### ISSUE TITLE
How to add/use lsphp81-dev 

### ISSUE THREAD

**Issue by torstent** [litespeedtech/ols-dockerfiles#4]
Hi, 

how can I use lsphp81-dev instead of lsphp81. 

I tried to get it with this Dockerfile commands:

````
RUN wget https://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh
# COPY enable_lst_debian_repo.sh ./enable_lst_debian_repo.sh
RUN bash enable_lst_debian_repo.sh

RUN apt install -y lsphp80-dev
````

But i get the error 

````
wget http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh
--2023-01-24 12:09:00--  http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh
Resolving rpms.litespeedtech.com (rpms.litespeedtech.com)... ::ffff:52.55.120.73, 52.55.120.73
Connecting to rpms.litespeedtech.com (rpms.litespeedtech.com)|::ffff:52.55.120.73|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-24 12:09:00 ERROR 404: Not Found.
````

But I can access the  http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh from my host os (also ubuntu) without any problem. So why does it not work inside the docker container?

**Comment by torstent** [comment]
It works with replacing http with https within enable_lst_debian_repo.sh


`RUN sed -i 's/http/https/g' enable_lst_debian_repo.sh`

resulting in:


```
FROM litespeedtech/openlitespeed:1.7.16-lsphp80
WORKDIR /var/www/vhosts
RUN apt update
RUN apt install -y wget

RUN wget https://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh
RUN sed -i 's/http/https/g' enable_lst_debian_repo.sh
RUN bash enable_lst_debian_repo.sh

RUN apt install -y lsphp80-dev
```

What I don't understand:
1) Why did it work without this line some month ago?
2) Why does this problem exists within a docker container / during docker build process but not in case I execute the same operations on my local ubuntu
3) I get the same error when executing this docker file (which seems to be used for generating the official docker images): https://github.com/litespeedtech/ols-dockerfiles/blob/master/template/Dockerfile

**Comment by Code-Egg** [comment]
Hi,

I did the same on my test server and there's no issue with https. Can not explain why it does not work on your server, maybe you can try to wget and curl from your local server and share here if it happens again. 

Will close the issue.
