### ISSUE TITLE
Version 1.8.* is not available

### ISSUE THREAD

**Issue by DuCun** [litespeedtech/ols-dockerfiles#8]
Versions 1.8.0 and 1.8.1 are not available
[https://openlitespeed.org/preuse/openlitespeed-1.8.0.tgz](https://openlitespeed.org/preuse/openlitespeed-1.8.0.tgz)
[https://openlitespeed.org/preuse/openlitespeed-1.8.1.tgz](https://openlitespeed.org/preuse/openlitespeed-1.8.1.tgz)
You can try to use the following resources, but after my testing, may not be able to get the latest patch later
[https://openlitespeed.org/packages/openlitespeed-1.8.1-x86_64-linux.tgz](https://openlitespeed.org/packages/openlitespeed-1.8.1-x86_64-linux.tgz)

**Comment by Code-Egg** [comment]
It will auto-build once v1.8.x labeled as stable. 
See https://openlitespeed.org/downloads/
